version: "3.9"
   
services:
  db:
    image: postgres
    container_name: postgres13
    ports:
      - "5433:5433"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5433

  web-employee:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: employee
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    restart: always
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5433
    depends_on:
      - db

