# Generated by Django 3.2.12 on 2022-03-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='department',
            field=models.CharField(blank=True, choices=[('-', '-----'), ('T', 'Tester'), ('D', 'Developer'), ('R', 'RH')], default='-', max_length=1, null=True, verbose_name='Name:'),
        ),
    ]
